# Generated by Django 6.0.8 on 2026-08-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
